export const {
  REACT_APP_GBC_CONTRACT_ADDRESS,
  REACT_APP_BSC_DECIMAL,
  REACT_APP_BSC_TESTNET_CONTRACT_ADDRESS,
  REACT_APP_METAMASK_PRIVATE_KEY,
  REACT_APP_WALLET_CONNECT_PROJECT_ID,
  REACT_APP_BSC_TESTNET_CHAIN_ID,
  REACT_APP_BSC_CHAIN_ID_HEX,
  REACT_APP_BSC_TESTNET_RPC_URL,
  REACT_APP_NETWORK_NAME,
  REACT_APP_BLOCK_EXPLORER_URL,
  REACT_APP_MESSAGE_FOR_SIGNING
} = process.env;
